name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Change this to the branch you want to analyze
  pull_request:
    branches:
      - main  # Change this to the branch you want to analyze

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install  # or use `yarn install` if you prefer yarn

      - name: Run tests and generate coverage
        run: npm test -- --coverage

      - name: SonarQube Scan
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # Add your SonarQube server URL here
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FIRST_REACT_APP }}  # Use your first token secret name here
        run: |
          npm install -g sonarqube-scanner
          sonar-scanner \
            -Dsonar.projectKey= first-react-project \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
            -Dsonar.login=${{ env.SONAR_TOKEN_FIRST_REACT_APP }} \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info  # Update this path to your coverage report location
